apiVersion: apps/v1
kind: Deployment
metadata: 
  name: second-app-deployment
  labels:
    group: example
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: second-app
      tier: backend
    # matchExpressions:
    #   - {key: app, operator: In, values: [second-app, first-app]}
    #   # - {key: app, operator: NotIn, values: [first-app]}
  template: 
    metadata:
      labels: 
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-nodejs
          image: diogoferreiranavia/kub-first-app:2
          imagePullPolicy: Always
          # image: diogoferreiranavia/kub-first-app:latest
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              # httpHeaders:
            periodSeconds: 10
            initialDelaySeconds: 5
        # - name: ...
        #   image: ...
    