apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  #type: ClusterIP #Usufull if it's only internal comunication
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
