apiVersion: v1
#This is a claim
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources: #Counter part to the capacity on the pv
    requests:
      storage: 1Gi